import type { AppStateSnapshot } from "@/lib/persistence/snapshot";

export function createDemoSeedSnapshot(now = new Date().toISOString()): AppStateSnapshot {
  return {
    demoPersistenceSchemaVersion: "d01-v1",
    children: [
      {
        id: "c-1",
        name: "林小雨",
        nickname: "小雨",
        birthDate: "2023-08-12",
        gender: "女",
        allergies: ["牛奶", "芒果"],
        heightCm: 96,
        weightKg: 14.2,
        guardians: [{ name: "林妈妈", relation: "母亲", phone: "138****1024" }],
        institutionId: "inst-1",
        className: "向阳班",
        specialNotes: "午睡前容易情绪波动，需要安抚绘本。",
        avatar: "👧",
        parentUserId: "u-parent",
      },
      {
        id: "c-2",
        name: "张浩然",
        nickname: "浩浩",
        birthDate: "2022-05-09",
        gender: "男",
        allergies: [],
        heightCm: 102,
        weightKg: 16.5,
        guardians: [{ name: "张爸爸", relation: "父亲", phone: "139****5678" }],
        institutionId: "inst-1",
        className: "向阳班",
        specialNotes: "喜欢搭建类活动，可强化精细动作训练。",
        avatar: "👦",
      },
      {
        id: "c-3",
        name: "陈思琪",
        nickname: "琪琪",
        birthDate: "2020-11-19",
        gender: "女",
        allergies: ["芒果"],
        heightCm: 111,
        weightKg: 18.3,
        guardians: [{ name: "陈奶奶", relation: "祖母", phone: "137****9921" }],
        institutionId: "inst-1",
        className: "晨曦班",
        specialNotes: "语言表达能力强，适合担任小组分享。",
        avatar: "👧",
      },
    ],
    attendance: [],
    meals: [],
    growth: [],
    feedback: [],
    health: [],
    taskCheckIns: [],
    interventionCards: [],
    consultations: [],
    mobileDrafts: [],
    reminders: [
      {
        reminderId: "reminder-c1-daily-feedback",
        reminderType: "family-task",
        targetRole: "parent",
        targetId: "c-1",
        childId: "c-1",
        title: "今晚反馈",
        description: "请反馈今晚在家的情绪和睡前配合情况。",
        scheduledAt: now,
        status: "pending",
        sourceId: "seed-d01",
      },
    ],
    tasks: [],
    messages: [
      {
        messageId: "msg-seed-parent-teacher-1",
        conversationId: "conv-c1-home-school",
        childId: "c-1",
        classId: "向阳班",
        senderRole: "parent",
        senderId: "u-parent",
        senderName: "林妈妈",
        receiverRole: "teacher",
        targetRole: "teacher",
        content: "小雨昨晚睡前有些抗拒，今天麻烦老师观察午睡前情绪。",
        createdAt: now,
        readBy: [],
        status: "sent",
      },
    ],
    conversations: [
      {
        conversationId: "conv-c1-home-school",
        childId: "c-1",
        classId: "向阳班",
        participantIds: ["u-parent", "u-teacher"],
        participantRoles: ["parent", "teacher"],
        status: "open",
        createdAt: now,
        updatedAt: now,
      },
    ],
    healthMaterials: [],
    nutritionMenus: [
      {
        menuId: "menu-xiangyang-today",
        date: now.slice(0, 10),
        classId: "向阳班",
        meals: {
          breakfast: ["小米粥", "蒸蛋"],
          lunch: ["米饭", "番茄牛肉", "青菜"],
          snack: ["苹果", "酸奶"],
        },
      },
    ],
    storybooks: [],
    updatedAt: now,
  };
}
